### ISSUE TITLE
Need for user content to go to rempte share (NFS/CIFS)

### ISSUE THREAD

**Issue by jus7incase** [arkOScloud/pkgbuilds#56]
Currently it is very high effort to configure all apps to story content on a remote NAS.
arkOS should provide for easy configuration so that all user content (emails, ownCloud files, cal, contacts, etc.) goes to a remote share (NFS or CIFS). This might be an encrypted share on a NAS.

Reason: to be able to re-install the arkOS node without data loss.

**Comment by peakwinter** [comment]
arkOScloud/core#16
